export const USERS = {
   FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
   FETCH_USERS_RECEIVE: 'FETCH_USERS_RECEIVE',
   ADD_NEW_USER: 'ADD_NEW_USER',
   DELETE_USER: 'DELETE_USER',
   UPDATE_USER_DETAILS_REQUEST: 'UPDATE_USER_DETAILS_REQUEST',
   UPDATE_USER_DETAILS_RECEIVE: 'UPDATE_USER_DETAILS_RECEIVE',
   DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
   DELETE_USER_RECEIVE: 'DELETE_USER_RECEIVE',
}

export const TODOS = {
   FETCH_REQUEST: 'FETCH_TODOS_REQUEST',
   FETCH_RECEIVE: 'FETCH_TODOS_RECEIVE',
}

export const POSTS = {
   FETCH_REQUEST: 'FETCH_POSTS_REQUEST',
   FETCH_RECEIVE: 'FETCH_POSTS_RECEIVE',
}