export const USERS = {
   FETCH_USERS_REQUEST: 'FETCH_USERS_REQUEST',
   FETCH_USERS_RECEIVE: 'FETCH_USERS_RECEIVE',
   ADD_NEW_USER: 'ADD_NEW_USER',
   UPDATE_USER_DETAILS_REQUEST: 'UPDATE_USER_DETAILS_REQUEST',
   UPDATE_USER_DETAILS_RECEIVE: 'UPDATE_USER_DETAILS_RECEIVE',
   DELETE_USER_REQUEST: 'DELETE_USER_REQUEST',
   DELETE_USER_RECEIVE: 'DELETE_USER_RECEIVE',
}